### ISSUE TITLE
community materials on the website

### ISSUE THREAD

**Issue by psteinb** [hpc-carpentry/hpc-carpentry.github.io#12]
I propose to add a new menu in the side pane to start collecting meeting notes, links to talks, possibly blog posts, etc. Please drop me a thumbs up if you are in favor!

**Comment by psteinb** [comment]
ok, I have to things coming up:
- a set of events happening at SC18:
https://sighpceducation.acm.org/sc18_education_list.html
where I see multiple events related to training in HPC 

- upcoming webinar:
https://sighpceducation.acm.org/trends_webinar.html

**Comment by psteinb** [comment]
Along these lines, I am thinking of add a `news` or `blog` section to the menu. This could then be the central point to log events and decisions.

**Comment by psteinb** [comment]
I'd love to bring up this issue again in to order to document future events such as the upcoming HPCCarpentry breakout at carpentrycon@home 2020 by @ocaisa and myself.

**Comment by psteinb** [comment]
@tkphd and @ocaisa there was no feedback to this so far. I think we should go ahead and add a news section to this website. I hope I find the time until mid July, 2020. :crossed_fingers:

**Comment by psteinb** [comment]
As a first post, we could add the agenda for the breakout session and our suggestions for moving forward. What do you think?

**Comment by tkphd** [comment]
Sounds good!

**Comment by ocaisa** [comment]
I'll make a stab at this right now.

**Comment by ocaisa** [comment]
Done in #17
