### ISSUE TITLE
Landing page?

### ISSUE THREAD

**Issue by psteinb** [hpc-carpentry/hpc-carpentry.github.io#13]
The content of the landing page irritates me. Can anyone provide me some feedback on where this is coming from, please? I'd love to replace it with something community related.

**Comment by ChristinaLK** [comment]
which page + what content specifically?

**Comment by psteinb** [comment]
Sorry, I mean [README.txt](https://github.com/hpc-carpentry/hpc-carpentry.github.io/blob/master/README.txt)

**Comment by ChristinaLK** [comment]
Yes!  Definitely.  If we want to keep that information, we could move it to a different file, but I agree that the README should be about the project and not the nuts + bolts of the website.

**Comment by psteinb** [comment]
done with #16
