### ISSUE TITLE
Request for write access

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/hpc-carpentry.github.io#23]
I do not seem to be able to contribute to this repo, and would like to be able to, please.

**Comment by ocaisa** [comment]
Hi @reid-a , anyone can contribute to this repo by [forking](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) and creating a [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests), you don't need any special rights. Even you did have write access, I would still recommend this workflow so we can review and discuss any changes you might want to make. If you need any help with the workflow let me know.

**Comment by ocaisa** [comment]
But judging by #24 you know that workflow, so maybe you mean you want the ability to merge PRs?

**Comment by ocaisa** [comment]
You're part of https://github.com/orgs/hpc-carpentry/teams/hpc-carpentry-github-io-contributors so you should have that right

**Comment by ocaisa** [comment]
Ah, you didn't have maintainer status there, I've updated that...this should be ok to close now?

**Comment by reid-a** [comment]
Yes indeed! My apologies, Trevor created a group and added me to it, this all got dealt with outside of the issue, and I neglected to come back and close it.

My apologies, and thanks for engaging!
