### ISSUE TITLE
Remodel the landing page on the main Carpentries site

### ISSUE THREAD

**Issue by ocaisa** [hpc-carpentry/hpc-carpentry.github.io#26]
The current page https://hpc-carpentry.github.io/ is a bit too basic for the things that we would probably like to do (and also has accessibility issues, see #22 ). We should consider instead adopting the template of https://github.com/carpentries/carpentries.org because I believe it brings quite a few benefits:
* It is probably already a familiar setup for many people
* It is battle-tested
* The contribution process is well documented
* We can benefit from upstream improvements
* We can leverage upstream experience

**Comment by psteinb** [comment]
I'd be in favor of this move!

**Comment by ocaisa** [comment]
I've started to work on this in [this repo](https://github.com/ocaisa/hpc-carpentry.org), and the site is currently being published at https://hpc-carpentry.org

It needs quite a bit of work, since a lot of the content that has been cloned from carpentries.org should be either removed, or provided as links to the original pages. I would really appreciate help in going through the menus, and figuring out what we should keep, what we should just link to and what we should remove.

**Comment by ocaisa** [comment]
And I would **really** appreciate if someone came up with a logo for HPC Carpentry

**Comment by ocaisa** [comment]
We did a complete remodel of the website based on the upstream Carpentries website. You can now find this at https://www.hpc-carpentry.org/ .The repo that creates that site is at https://github.com/hpc-carpentry/hpc-carpentry.org

The logo is still an ongoing thing, but now that the repo is under the organisation I think we can close this
