### ISSUE TITLE
Contact Us page not rendering properly

### ISSUE THREAD

**Issue by ocaisa** [hpc-carpentry/hpc-carpentry.github.io#26]
See http://www.hpc-carpentry.org/contact/

**Comment by ocaisa** [comment]
It's rendered as code because Jekyll picks up the indentation and assumes that's what it is. Removing the indentation fixes the issue (but isn't exactly satisfactory).

With #22, there may be other cases of this...

**Comment by tkphd** [comment]
Hmmm. The file does have  a `.md` extension, so perhaps Jekyll is not entirely wrong. Instead of fixing the HTML, I think we should convert it to Markdown and add blurbs for GitHub/coordination, Slack, Topicbox, and Twitter.

**Comment by ocaisa** [comment]
I don't have time to do that now, rather than leave the Contact Us non-functional how about we merge this for now and open an issue for the Markdown conversion?
