### ISSUE TITLE
branch protection

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-carpentry.github.io#29]
The branches in this repo are not [protected](https://docs.github.com/en/github/administering-a-repository/about-protected-branches).
* The `main` branch should require at least one approving review.
* If possible, the `gh-pages` branch should only be writable by Netlify.

**Comment by tkphd** [comment]
Merges to `main` now require 1 approving review, and for all checks to pass.

**Comment by ocaisa** [comment]
Just to mention, we don't use Netlify to deploy to `gh-pages`, in our case we are using a GitHub Action to do that, see https://github.com/hpc-carpentry/hpc-carpentry.github.io/blob/main/.github/workflows/build-and-deploy.yml#L53
