### ISSUE TITLE
migration checks

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/hpc-carpentry.github.io#5]
- Has the existing content been migrated over from [hpc-carpentry/hpc-carpentry.github.io](https://github.com/hpc-carpentry/hpc-carpentry.github.io)?
- Is this repo publicly visible?
- Can new blog posts be submitted by community members?
- Does the new site successfully build?

**Comment by ocaisa** [comment]
Regarding the first point...no not everything has been transferred over. The redesign was mostly tailoring the Carpentries template to reflect HPC Carpentry. Specific things that we should probably find a home for are:
- [ ] https://hpc-carpentry.github.io/workshops
- [ ] https://hpc-carpentry.github.io/why-hpc-carpentry
- [ ] https://hpc-carpentry.github.io/about
- [ ] https://hpc-carpentry.github.io/our-lessons (this [actually exists](https://www.hpc-carpentry.org/community-lessons/#lessons-in-the-hpc-carpentry-incubator) but we need to figure out how to sync the content )

**Comment by tkphd** [comment]
AFAICT, the "new" website is fully populated, and not everything that was on the old site actually needs to be transferred over.
