### ISSUE TITLE
using `orgs` API to try to access user repositories

### ISSUE THREAD

**Issue by tobyhodges** [hpc-carpentry/hpc-carpentry.github.io#62]
The website builds are currently failing, due to the changes made to `feeds/other_lessons.R` in [13a0ea3](https://github.com/hpc-carpentry/hpc-carpentry.github.io/commit/13a0ea3a290c17a5b881f00283dca2adef8822e3).

The problem is that the `get_org_topics` function used on line 47 of that file

```
  frobnitzem <- get_org_topics("frobnitzem")
```

uses [the `get_list_repos` function defined in `feeds/utils.R`](https://github.com/hpc-carpentry/hpc-carpentry.github.io/blob/7002f34d8556b804816fe91457cf09d9f942a1d0/feeds/utils.R#L22), which makes a call to the GitHub _organizations_ API, to try to get a list of repositories for an organisation. `frobnitzem` is a _user_ account, so should be queried via the _users_ API. See the difference between the current call that is being made

https://api.github.com/orgs/frobnitzem/repos

and the result of the equivalent call made via the users API

https://api.github.com/users/frobnitzem/repos

I am fairly certain that this is the _problem_, but less confident about the best _solution_. I suppose you would need to adjust `get_list_repos` to accept an optional parameter that tells it to query the users API instead of the orgs API?

**Comment by tkphd** [comment]
Thanks for digging into this @tobyhodges! I think I have a fix ...
