### ISSUE TITLE
Lesson links are outdated

### ISSUE THREAD

**Issue by bkmgit** [hpc-carpentry/hpc-carpentry.github.io#74]
List of lessons at https://www.hpc-carpentry.org/community-lessons/ is outdated,
in particular workflows lesson is in the incubator.

**Comment by tkphd** [comment]
"HPC Workflows" appears twice -- once for the current, Workbench version of the lesson, and once for the old __hpc-python__ lesson.

**Comment by reid-a** [comment]
More specifically, for instance, the workflow lesson is listed twice, once under "Lessons in the Carpentries Incubator", with the heading "Creating HPC Workflows using Snakemake", and again in the "Lessons under HPC Carpentry", with the heading "Scaling studies on high-performance clusters using snakemake workflows." Both of these entries point to the same rendered lesson, the new Snakemake workflow one, but they have different repos, the first one is the currently-active workflow repo, and the second one points to the archived version of the Snakemake lesson we started with.

The content on this page is generated by a complicated process that I, at least, don't understand.

At a minimum, the repo sites and repostiory URLs should match, and possibly the archived lesson should be removed. Also the process by which this page is built should be more widely known.

**Comment by reid-a** [comment]
Addendum: As a first cut, @tkphd has tried un-archving the lesson, fixing the site URL, and re-archiving. Possibly our site will gather consistent data and the site and repo will at least match.

**Comment by reid-a** [comment]
Further addendum: The list is built by searching a list of github organizations for repositories with particular tags, so a fix for the particular apparent duplication of Snakemake is to remove the "lesson" tag from the archive.

**Comment by tkphd** [comment]
By removing the `lesson` tag from __old-hpc-workflows__ and rebuilding the website, @ocaisa removed the offending lesson from the website list.

**Comment by reid-a** [comment]
Removed the lesson tag from the problem lesson, it's now gone from the site. The rest of the lesson list is consistent, although some of them are pretty old and not getting a ton fo attention. That's an issue, but it's out of scope of this issue. Closed.
