### ISSUE TITLE
LLNL blog post exists but is a bit sparse

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/hpc-carpentry.github.io#86]
I'm struggling a bit with the long-promised LLNL blog post. A version is on the `llnl_blog_post` branch of this repo, I'm reaching out especially to @tkphd and @xorJane (who were there) to maybe help punch it up a bit, but input from anyone would be welcome. Thanks!

**Comment by reid-a** [comment]
Updated this a bit in collaboration with @tkphd, letting it marinate a bit so @xorJane can have a say. It's much better now.

**Comment by tkphd** [comment]
Closed by #87.
