### ISSUE TITLE
HPC Shell missing from landing page

### ISSUE THREAD

**Issue by symulation** [hpc-carpentry/hpc-carpentry.github.io#9]
With the division of the original day into two sections (a good move) the landing page is now missing one of the possible HPC Carpentry modules:  HPC Shell.

**Comment by ChristinaLK** [comment]
I think this is in my open PR.

**Comment by psteinb** [comment]
The code of #6 looks good, but I have a hard time testing it. Do I need to build this website somehow? If so, how?

**Comment by razoumov** [comment]
On your laptop:
git clone https://github.com/hpc-carpentry/hpc-carpentry.github.io
cd hpc-carpentry.github.io
git checkout -b ChristinaLK-adding-lesson master
git pull https://github.com/ChristinaLK/hpc-carpentry.github.io.git adding-lesson
jekyll serve
open http://localhost:4000 in your browser

**Comment by psteinb** [comment]
Yes, I found that this is a Jekyll based site by experimentation. See #11.

**Comment by psteinb** [comment]
Fixed in #6
